version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "vgabrielsoares"
    assignees:
      - "vgabrielsoares"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignorar atualizações major para evitar breaking changes
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      vue-ecosystem:
        patterns:
          - "vue*"
          - "@vue/*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "@vue/test-utils"
        update-types:
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "vue-tsc"
        update-types:
          - "minor"
          - "patch"
      vite-ecosystem:
        patterns:
          - "vite*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "vgabrielsoares"
    assignees:
      - "vgabrielsoares"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
